### ISSUE TITLE
Help me how to use this script

### ISSUE THREAD

**Issue by sadazs** [lucifer1004/autochess#3]
Hi Lucifer!
I try to start script but it error, Can help me how to use this script?
Many thank
![image](https://user-images.githubusercontent.com/40275407/54969875-912e1480-4fb2-11e9-9f8c-383cc38eb156.png)

**Comment by lucifer1004** [comment]
You should use npm run serve instead of dev.




| |
吴自华
邮箱：qqbbnease1004@126.com
|

签名由 网易邮箱大师 定制

On 03/26/2019 11:34, sadazs wrote:

Hi Lucifer!
I try to start script but it error, Can help me how to use this script?
Many thank
